# Generated by Django 4.1.7 on 2023-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_users_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
    ]
