# Generated by Django 4.1.7 on 2023-10-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_users_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='products',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='store.products'),
        ),
    ]
