# Generated by Django 4.1.7 on 2023-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_users_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='products',
        ),
        migrations.AddField(
            model_name='users',
            name='products',
            field=models.ManyToManyField(default='none', related_name='user_products', to='store.products'),
        ),
    ]
